from ast import literal_eval

"""
we should store every thing in this
just bahmany allows to run codes
it means codes generated by bahmany only allow to run


"""


class PythonRunner:

    def __init__(self):
        pass

    def runPythonFromUserTask(self, this, pythonCodes):
        if this.lunchedProcessInstance.bpmn["user_id"] == 89:
            exec(pythonCodes)
        else:
            raise Exception("Creator of this task is not Bahmany. Just Bahmany is allowed to run service task")

    def runServiceTaskPython(self, this, pythonCodes):
        if this.lunchedProcessInstance.bpmn["user_id"] == 89:
            exec(pythonCodes)
        else:
            raise Exception("Creator of this task is not Bahmany. Just Bahmany is allowed to run service task")

    def runDataTableValuePython(self, this, pythonCodes):
        if this.dataTableCreatorPositionInstance.userID == 89:
            exec(pythonCodes)
        else:
            raise Exception("Creator of this task is not Bahmany. Just Bahmany is allowed to run service task")
