def fixChar(currentChar):
    cc = currentChar
    cc = cc.replace("ش", "ش")
    cc = cc.replace("ر", "ر")
    cc = cc.replace("ک", "ک")
    cc = cc.replace("ت", "ت")
    cc = cc.replace("ي", "ی")
    cc = cc.replace("ي", "ی")
    cc = cc.replace("گ", "گ")
    cc = cc.replace("س", "س")
    cc = cc.replace("م", "م")
    cc = cc.replace("غ", "غ")
    cc = cc.replace("ا", "ا")
    cc = cc.replace("آ", "آ")
    cc = cc.replace("ذ", "ذ")
    cc = cc.replace("ن", "ن")
    cc = cc.replace("خ", "خ")
    cc = cc.replace("ل", "ل")
    cc = cc.replace("پ", "پ")
    cc = cc.replace("ه", "ه")
    cc = cc.replace("ص", "ص")
    cc = cc.replace("ع", "ع")
    cc = cc.replace("د", "د")
    cc = cc.replace("و", "و")
    return cc
